### ISSUE TITLE
Update Zendesk theme based on designs

### ISSUE THREAD

**Issue by briangrossman** [mitodl/ocw-zendesk-theme#1]
We have a design for the Zendesk support center for OCW. It can be found [here](https://projects.invisionapp.com/share/3Z123TYWM64W#/screens/459218314_Zendesk_-_Help_-_FAQs). I've included a screenshot below. 

Please update the theme to match the proposed design. See Acceptance Criteria for details.

@arslanashraf7 set up a test site for this PR: https://github.com/mitodl/mitxonline-zendesk-theme/pull/4 to view the work he had done. Doing this would be helpful for this issue as well.

--------------------

**Design**
![image](https://user-images.githubusercontent.com/21342568/147391096-87ed6cd4-8fb0-435f-844e-35259859b35f.png)

--------------------

**Acceptance Criteria**
- [ ] Match the designs to the [InVision mock up](https://projects.invisionapp.com/share/3Z123TYWM64W#/screens/459218314_Zendesk_-_Help_-_FAQs)
- [ ] `Submit a request` link (upper right) will open a page to submit a new support request ([xPRO example](https://xpro.zendesk.com/hc/en-us/requests/new))
- [ ] The number of buttons (that currently read: `Label of button`) and their text are not yet determined. Ensure the color and font are correct.
- [ ] Use fonts (and colors, if necessary) that match the OCW site.
- [ ] The title of page should be `Support Center` rather than `Help & FAQs`
- [ ] Add a `Can't find what you're looking for?` section, similar to xPRO. Just above the footer. 
   - [ ] The horizontal rule should use the red color from the search button
   - [ ] The contact use button should use the red color form the search button and have white text
   - [ ] The section background-color should be white
   - [ ] Clicking `Contact Us` will open a page to submit a new support request ([xPRO example](https://xpro.zendesk.com/hc/en-us/requests/new)) 
![image](https://user-images.githubusercontent.com/21342568/147391544-04d3e111-06a4-4431-9b7f-2f8585ae4b81.png)
- [ ] The footer should match the OCW site footer

Let me know if I missed anything

**Comment by Wassaf-Shahzad** [comment]
@briangrossman Could you kindly point me to the OCW footer., A design prototype or a screenshot will do.
@nicolaeherrera. I was unable to fine the hero image in the Invision assets would you kindly share the link for it.

**Comment by briangrossman** [comment]
@Wassaf-Shahzad 
You can use the footer in the InVision design for the page. The `Link Label`s should be:
- **Accessibility** - link: https://accessibility.mit.edu/
- **Creative Commons License** - link: https://creativecommons.org/licenses/by-nc-sa/4.0/
- **Privacy and Terms of Use** - link: https://ocw.mit.edu/terms/ (this may change, but you can use this for now)

**Comment by briangrossman** [comment]
@Wassaf-Shahzad This is looking great. Everything looks perfect so far. 

I'm trying to get you the hero image.

**Comment by briangrossman** [comment]
@Wassaf-Shahzad 

You should now be able to download the hero image via the Inspect mode in InVision. Here it is. 
![OCW_ZD_Hero](https://user-images.githubusercontent.com/21342568/148087000-87083478-188e-4555-bb64-23778fc73766.jpg)

**Comment by Wassaf-Shahzad** [comment]
> @Wassaf-Shahzad
> 
> You should now be able to download the hero image via the Inspect mode in InVision. Here it is. ![OCW_ZD_Hero](https://user-images.githubusercontent.com/21342568/148087000-87083478-188e-4555-bb64-23778fc73766.jpg)

Updated image and PR is ready to be reviewed.
